- name: ec2-instances creation 
  hosts: localhost
  connection: local
  vars:
    ami_id: ami-0220d79f3f480ecf5
    sg_id: sg-04da36c125d32be89
    zone_id: "Z082277119F6MYLF9ANO8"
    domain_name: practisedevops.shop
    instances:
    - mongodb
    - catalogue
  tasks:
    - name: create ec2-instance
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        instance_type: t3.micro
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        wait : true  #aws will wait until the instances are created completely and then move to next task
        tags:
          Name: "{{ item }}"
      loop: "{{ instances }}"
      register: ec2_output
    - name: Display instance details
      ansible.builtin.debug:
        msg: "{{ ec2_output }}"
    - name: Add a r53 record 
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ item.item }}.{{ domain_name }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
        overwrite: true
      loop: "{{ ec2_output.results }}"
        
          
          