- name: frontend server
  hosts: frontend
  become: yes
  tasks:
  - name: Disable the Node.js DNF module
    ansible.builtin.command: dnf module disable nginx -y
  - name: enable the Node.js DNF module
    ansible.builtin.command: dnf module enable nginx:1.24 -y
  - name: install the Node.js DNF module
    ansible.builtin.command: dnf module install nginx -y
  - name: start and Enable nginx
    ansible.builtin.service:
      name: nginx
      enabled: yes
  - name: Remove default html
    ansible.builtin.file:
      path: /usr/share/nginx/html/*
      state: absent
  - name: Download zip file 
    ansible.builtin.unarchive:
      src:  https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip 
      dest: /usr/share/nginx/html 
      remote_src: yes
  - name: Copy nginx.conf
    ansible.builtin.copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
  - name: Restart service frontend
    ansible.builtin.service:
      name: frontend
      state: restarted