[mongodb]
mongodb.practisedevops.shop

[catalogue]
catalogue.practisedevops.shop

[redis]
redis.practisedevops.shop

[mysql]
mysql.practisedevops.shop

[shipping]
shipping.practisedevops.shop

[cart]
cart.practisedevops.shop

[user]
user.practisedevops.shop

[rabbitmq]
rabbitmq.practisedevops.shop

[payment]
payment.practisedevops.shop

[frontend]
practisedevops.shop

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321